config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github", views.github_login, name="github-login"),
    path("login/github/callback", views.github_callback, name="github-callback"),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path(
        "update-password/", views.UpdatePasswordView.as_view(), name="update-password"
    ),
]

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-semibold text-gray-400 flex flex-col">
    <span>
        Please don't copy us.
    </span>
    <span>
        &copy: Nbnb, Inc. All rights reserved.
    </span>
</footer>

templates/partials/header.html
<a href="{% url 'core:home' %}">Nbnb</a>
<ul>
    <li><a href="#">Login</a></li>
</ul>

templates/partials/messages.html
{% if messages %}
<ul class="absolute top-0 mx-auto left-0 right-0 flex justify-center">
    {% for message in messages %}
    <li
        class="message font-medium bg-gray-700 rounded-full z-10 text-white py-4 px-6 w-64 text-center {% if message.tags %}{{ message.tags}}{% endif %}">
        {{ message }}</li>
    {% endfor %}
</ul>

{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-medium h-full">
    {% if user.is_authenticated %}
    <li class="nav_link"><a href="{{ user.get_absolute_url }}">Profile</a></li>
    <li class="nav_link"><a href="{% url 'users:logout' %}">Log Out</a></li>
    {% else %}
    <li class="nav_link">
        <a href="{% url 'users:login' %}">Log in</a>
    </li>
    <li class="nav_link"><a href="{% url 'users:signup' %}">Sign Up</a></li>
    {% endif %}
</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github-login' %}" class="btn text-white bg-purple-600 border-purple-700 mb-2">
        <i class="fab fa-github mr-2 fa-lg"></i>
        Continue with Github
    </a>
    <a href="{% url 'users:kakao-login' %}" class="btn text-white bg-yellow-400 border-yellow-500 mb-2">
        <i class="fas fa-comment mr-2 fa-lg text-white"></i>
        Continue with Kakao
    </a>

    <div class="flex items-center w-full my-4">
        <div class="h-px w-full bg-gray-400"></div>
        <span class="text-gray-500 font-semibold mx-4 text-md">or</span>
        <div class="h-px w-full bg-gray-400"></div>
    </div>
</div>